steps:
  # ===========================================================================
  # Install Dependencies
  # ===========================================================================

  install:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm ci
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Type Check
  # ===========================================================================

  typecheck:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm run typecheck
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Build
  # ===========================================================================

  build:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm run build
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Test
  # ===========================================================================

  test:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm test -- --run
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Lint
  # ===========================================================================

  lint:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm run lint
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Format Check
  # ===========================================================================

  format:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm run format:check
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]
