steps:
  # ===========================================================================
  # Install Dependencies
  # ===========================================================================

  install:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm ci
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Type Check
  # ===========================================================================

  typecheck:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm run typecheck
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Build
  # ===========================================================================

  build:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm run build
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Test
  # ===========================================================================

  test:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm test -- --run
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Lint
  # ===========================================================================

  lint:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm run lint
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Format Check
  # ===========================================================================

  format:
    image: node:22-alpine
    commands:
      - apk add --no-cache git
      - npm run format:check
    depends_on:
      - install
    when:
      - event: [push, pull_request, manual, tag]

  # ===========================================================================
  # Publish to Codeberg npm Registry (on tag events only)
  # Codeberg is the source of truth - packages are published here
  # ===========================================================================

  publish:
    image: node:22-alpine
    environment:
      CODEBERG_TOKEN:
        from_secret: CODEBERG_TOKEN
    commands:
      - apk add --no-cache git
      - |
        echo "@nope-at:registry=https://codeberg.org/api/packages/nope-at/npm/" > .npmrc
        echo "//codeberg.org/api/packages/nope-at/npm/:_authToken=$CODEBERG_TOKEN" >> .npmrc
        cat .npmrc
        echo "Publishing to Codeberg npm registry..."
        npm publish --scope=@nope-at --access public
    depends_on:
      - typecheck
      - build
      - test
      - lint
      - format
    when:
      - event: tag
